root /var/www/swarm-space;
index index.html;

location / {
    try_files $uri $uri/ /index.html;
}

location = /index.html {
    add_header Cache-Control "no-cache";
}

location ~* \.(?:wasm|js|css|woff2?|ttf)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
}
