root /var/www/swarm-space;
index index.html;

gzip on;
gzip_min_length 1024;
gzip_types application/wasm text/css text/javascript application/javascript;

location / {
    try_files $uri $uri/ /index.html;
}

location = /index.html {
    add_header Cache-Control "no-cache";
}

location = /app.js {
    add_header Cache-Control "no-cache";
    try_files $uri =404;
}

location ~* \.(?:wasm|js|css)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
}
